Tapered sections
BHoM/RFEM_Toolkit pull request #117
Opened 2021-04-15 11:49 UTC by MartinHenriksen

### Issues addressed by this PR

 Closes #
closes #115 
closes #116 

 
added feature to read tapered sections from RFEM and fixed bug when reading rigidlinks with coupling type set. 

 ### Test files

[test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/RFEM_Toolkit-TaperedSections.gh?csf=1&web=1&e=aHHTK5)
RFEM file not shared here due to confidentiality

 ### Changelog

added feature: read tapered sections
fixed bug: rigid link with type coupling

2021-04-15 11:54 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-04-15 12:22 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-04-15 12:22 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-04-15 12:54 UTC, staintono submitted a review, later dismissed
looks good, doesnt throw any red error messages anymore

2021-04-15 15:28 UTC, MartinHenriksen commented
made small changes to satisfy code-compliance check. @staintono please re-submit your review

2021-04-15 15:37 UTC, staintono submitted a review, later dismissed
lgtm

2021-04-15 17:33 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-04-15 19:17 UTC, FraserGreenroyd requested changes
See comment. As comment relates only to compliance, I am happy to approve once checks go green providing only commits are to versioning and not functionality to save you finding a re-review @MartinHenriksen :smile:

2021-04-15 19:17 UTC, FraserGreenroyd commented on RFEM_Engine/Compute/Profile.cs
> +    public static partial class Compute
Sorry @MartinHenriksen - this change needs to be versioned. Easiest way is with a `PreviousVersion` attribute I suspect! Gimme a shout if you need any help, happy to support :smile:

2021-04-16 07:48 UTC, MartinHenriksen commented on RFEM_Engine/Compute/Profile.cs
> +    public static partial class Compute
Thanks @FraserGreenroyd I have added the attribute

2021-04-16 07:48 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-04-16 08:18 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-04-16 08:19 UTC, FraserGreenroyd commented
@BHoMBot check serialisation

2021-04-16 08:22 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-04-16 08:22 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-04-16 08:33 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2360466119

2021-04-16 08:34 UTC, FraserGreenroyd approved these changes
Approving on a versioning check and using functionality review from previously as discussed with @MartinHenriksen as last commit is only a versioning fix :smile:

2021-04-16 08:47 UTC, merged