Issue18 name property
BHoM/RFEM_Toolkit pull request #133
Opened 2022-04-26 11:25 UTC by Arne-Martensen

### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #

 

 ### Test files

 ### Changelog

 ### Additional comments

2022-04-27 14:16 UTC, MartinHenriksen commented on RFEM_Adapter/Convert/FromRFEM/SectionProperty.cs
> +            sectionName.GetType().ToString();
This does nothing. Please remove it

2022-04-27 14:18 UTC, MartinHenriksen commented on RFEM_Adapter/Convert/ToRFEM/Node.cs
> +            rfNode.Comment = node.Name;
remove this line - no point in setting name twice

2022-04-27 14:20 UTC, MartinHenriksen requested changes
please see comments for changes

2022-04-27 15:02 UTC, Arne-Martensen commented on RFEM_Adapter/Convert/FromRFEM/SectionProperty.cs
> +            sectionName.GetType().ToString();
Line has been removed.

2022-04-28 10:42 UTC, MartinHenriksen approved these changes
LGTM

2022-04-28 10:44 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-04-28 10:46 UTC, FraserGreenroyd requested changes
@MartinHenriksen can you provide more details on how you have reviewed this please (code review only? Run a test file? etc.?)

@Arne-Martensen can you provide a more suitable PR title for the change log please?

2022-04-28 11:15 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-04-28 12:13 UTC, MartinHenriksen approved these changes
Code reviewed and new features tested using the test files supplied. All works as expected.

2022-04-28 12:19 UTC, closed without merging