Fix Pull of Constraint6DOF. Pull of DOFType (Fixed,Free, Spring) and …
BHoM/RFEM_Toolkit pull request #136
Opened 2022-05-04 11:06 UTC by Arne-Martensen

…Stiffness.

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #13 

 
#13: Push and Pull of ConstraintDOF elements has been altered so that the user is now able to push supports with either the DOFType Fixed, Free or Spring. When spring is chosen the corresponding stiffness will be set. An analog feature for the pull has been implemented. When a dimension (x, y or z) is set to be fixed the stiffens received is set to -1 while free is represented by 0. If the constraint in RFEM is a spring a double number is assigned to the corresponding parameter.

 ### Test files

 ### Changelog

 ### Additional comments

2022-05-04 13:41 UTC, MartinHenriksen requested changes

2022-05-04 13:41 UTC, MartinHenriksen commented on RFEM_Adapter/Convert/FromRFEM/Constraint.cs
> +                bhConstraint.RotationalStiffnessX = -1;
... same with rotation

2022-05-04 13:47 UTC, Arne-Martensen commented on RFEM_Adapter/Convert/FromRFEM/Constraint.cs
> +                bhConstraint.TranslationalStiffnessX = -1;
I'm assuming the same is the case where the translation is set to free. Then the stiffness should not be 0?

2022-05-04 14:56 UTC, MartinHenriksen commented on RFEM_Adapter/Convert/FromRFEM/Constraint.cs
> +                bhConstraint.TranslationalStiffnessX = -1;
no, stiffness should be 0 for both free and fixed

2022-05-04 15:23 UTC, MartinHenriksen commented
@BHoMBot check ready-to-merge

2022-05-05 08:33 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-05-05 10:49 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-05-05 10:53 UTC, merged