Panels with curved outline can't be pulled
BHoM/RFEM_Toolkit pull request #141
Opened 2022-05-17 14:02 UTC by Arne-Martensen

### Issues addressed by this PR

Before it was not possible to pull/push panels or openings with a curved outline. It was also not possible to pull bars with sections of type Rectangle, Pipe, Circle or Round when working in the german version of RFEM. 

 Closes #139 #140 

 
139: This PR should enable the user to pull/push panels and openings contanint of either plane polylines (which was also possible previously), arches circles or a combination of polylines and arcs.  

140: It should also be possible to pull bars with sections of type Rectangle, Pipe, Circle or Round when working in the german version of RFEM. 

 ### Test files

[Test File 139](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/RFEM_Toolkit_Elements%20with%20curved%20geometry%20cant%20be%20pulled.gh?csf=1&web=1&e=YmSIa0)
[Test File 140](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/Issue%20139_files?csf=1&web=1&e=5w0fLs)

 ### Additional comments
139: Please make sure that your RFEM window is "Blank". The current version is not able to overwrite the RFEM model so you will receive an error message in GH. 
140: When testing for issue 140 it is neccesary to change the language in RFEM to german (see [link](https://www.dlubal.com/zh/downloads-and-information/documents/online-manuals/rfem-5/10/01/12)). 

### Changelog

- Adding functionality to read panels with a circular/arched panels and opening outline. 
- Adding functionality to write panels with a circular/arched panels and opening outline.
- Adding a dictionary to enable the pull of the mentioned cross sections.

2022-06-13 09:24 UTC, staintono submitted a review, later dismissed
Using the provided test file panels and openings with curved outlines can be successfully pushed and pulled.

2022-06-24 12:41 UTC, MartinHenriksen requested changes
Functionality works, but some code improvements can be done

2022-06-24 12:41 UTC, MartinHenriksen commented on RFEM_Adapter/CRUD/Read/Panel.cs
> +                    Engine.Base.Compute.RecordError("Import of the chosen panel shape is currently not supported!");
we should add description of type, so user knows what is not supported

2022-06-24 12:41 UTC, MartinHenriksen commented on RFEM_Adapter/CRUD/Read/Panel.cs
> +                if (modelData.GetLine(edgeId, rf.ItemAt.AtNo).GetData().Type.Equals(rf.LineType.PolylineType))
each of these if-statements makes 3 COM-calls to get the same line data. We could refactor to make this cleaner and faster

2022-06-24 12:41 UTC, MartinHenriksen commented on RFEM_Adapter/CRUD/Read/Panel.cs
> +
this whole method is almost a straight copy of 'GetEdgesFromRFEMSurface'. This might be able to be refactored to a single method that takes 'boundaryString' as argument

2022-07-25 07:17 UTC, Arne-Martensen commented on RFEM_Adapter/CRUD/Create/Panel.cs
> +        public List<rf.Line> GenerateOutlineLines(List<Edge> edgeList)
Method has been canged to private.

2022-07-25 08:38 UTC, Arne-Martensen commented on RFEM_Adapter/CRUD/Read/Panel.cs
> +                if (modelData.GetLine(edgeId, rf.ItemAt.AtNo).GetData().Type.Equals(rf.LineType.PolylineType))
The 3 COM-calls in the if-statements have been reduced to a single one.

2022-07-25 08:51 UTC, Arne-Martensen commented on RFEM_Adapter/CRUD/Read/Panel.cs
> +                    Engine.Base.Compute.RecordError("Import of the chosen panel shape is currently not supported!");
The description of the edge type is added to the error message.

2022-07-25 12:05 UTC, Arne-Martensen commented on RFEM_Adapter/CRUD/Read/Panel.cs
> +
The two methods 'GetEdgesAsCurveFromOpenings' and 'GetEdgesFromRFEMSurface' have been replaced by the function 'GetBoundaryEdges'.

2022-07-28 15:07 UTC, staintono approved these changes
Using the provided test file panels and openings with curved outlines can be successfully pushed and pulled. 

With RFEM set to German bars can now be pulled successfully as explicit sections

2022-08-01 14:02 UTC, MartinHenriksen approved these changes
Code reviewed and looks good. no change in functionality, all still works as expected.

2022-08-01 14:03 UTC, MartinHenriksen commented
@BHoMBot check ready-to-merge

2022-08-01 14:09 UTC, MartinHenriksen commented
@BHoMBot check required

2022-08-01 16:10 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

2022-08-01 16:12 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 7615384749

2022-08-01 16:12 UTC, merged